# Generated by Django 4.0.1 on 2023-10-25 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalmanagement', '0002_appointment_prescription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='date_time',
        ),
        migrations.AddField(
            model_name='appointment',
            name='date',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='appointment',
            name='time',
            field=models.TimeField(default=None),
        ),
    ]
