# Generated by Django 4.0.1 on 2023-10-30 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalmanagement', '0003_remove_appointment_date_time_appointment_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='symptoms',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialization',
            field=models.CharField(choices=[('Cardiologist', 'cardiologist'), ('Dermatologists', 'dermatologists'), ('Emergency Medicine Specialists', 'emergency medicine specialists'), ('Allergists/Immunologists', 'allergists/immunologists'), ('Anesthesiologists', 'anesthesiologists'), ('ENT Specialist', 'ent'), ('Neurologist', 'neurologist')], max_length=50),
        ),
    ]
