# Generated by Django 4.0.1 on 2023-10-31 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalmanagement', '0004_appointment_symptoms_alter_doctor_specialization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('Booked', 'BOOKED'), ('Closed', 'CLOSED'), ('Cancelled', 'CANCELLED')], max_length=255),
        ),
    ]
